.PHONY: pre-install
.SILENT:
pre-install:

.PHONY: post-install
.SILENT:
post-install:
	@mkdir -p ~/.emacs.d/vendor

.PHONY: pre-uninstall
.SILENT:
pre-uninstall:

.PHONY: post-uninstall
.SILENT:
post-uninstall:
