.PHONY: pre-install
.SILENT:
pre-install:

.PHONY: post-install
post-install:
	@ln -s ~/.config/Code ~/.config/Code\ -\ OSS

.PHONY: pre-uninstall
.SILENT:
pre-uninstall:

.PHONY: post-uninstall
.SILENT:
post-uninstall:
